### ISSUE TITLE
Difference between spec and test suite in regards to `ASC_CDL` `style`

### ISSUE THREAD

**Issue by vincentisambart** [ampas/aces-docs#19]
As I'm trying to implement the spec, I've been running my parsing code on the [CLF File Test Suite](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/tests/data/files/clf) mentioned in the [Implementation Guide](https://docs.acescentral.com/guides/clf/).

In that test suite, in [cdl_missing_style.clf](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/tests/data/files/clf/cdl_missing_style.clf), `ASC_CDL` has no `style` attribute and the description says `Missing style defaults to "Fwd"`. However, the [`ASC_CDL` section](https://docs.acescentral.com/specifications/clf/#asc_cdl) of the spec says that `style` is required without any mention of a default value.

If the test suite is correct, it seems to me that `ASC_CDL`'s `style` should be marked as optional with the default value mentioned, as is the case for `Range`'s `style`.

Also some minor thoughts I had reading the spec:
- `Substititues` should be `Substitutes` ([6. section title](https://docs.acescentral.com/specifications/clf/#substititues-for-processnode))
- `when nit` should be `when it` ([Matrix section](https://docs.acescentral.com/specifications/clf/#matrix))
- `color com- ponents` should be `color components` ([LUT3D section](https://docs.acescentral.com/specifications/clf/#lut3d))
- `style (required` has a missing closing bracket and should be `style (required)` ([Log section](https://docs.acescentral.com/specifications/clf/#log))
- not a typo, but formatting-wise, `maxOutValue (optional)` should probably be followed by new line to be like the other elements of `Range` ([Range section](https://docs.acescentral.com/specifications/clf/#range))
- what is called `scale factor` in the [Bit Depth section](https://docs.acescentral.com/specifications/clf/#bit-depth) is used with a different name `SIZE` in the formulas of the [Range section](https://docs.acescentral.com/specifications/clf/#range). I thought calling it `scaleFactor` in those formulas would make it clearer they are the same.
- Among all process node substitutes sections, only the [`Exponent` section](https://docs.acescentral.com/specifications/clf/#exponent) explicitly mentions the `Description` element (with a link to [ProcessNode](https://docs.acescentral.com/specifications/clf/#processNode)). I think you could remove `Description` from the `Exponent` section for consistency.
- In the [`Range` section](https://docs.acescentral.com/specifications/clf/#range), at the end of the description you are told that values must be set such that `maxOutValue = maxInValue × bitDepthScale`. From the context you can understand that if only the minimum value pair is provided, it is `minOutValue = minInValue × bitDepthScale`, but that I thought that maybe could be explicit, or written something like `OutValue = InValue × bitDepthScale`

Thanks

**Comment by scottdyer** [comment]
Once again, your attention to detail and suggested fixes are appreciated. 

Not quite sure how the "required" slipped into the `style` attribute under `ASC_CDL`. However, I think the intent was for it to be optional, and assume if it is not present that the `"Fwd"` style was desired. This is how it was written in the schema and in the test files, so I think the spec was in error. I have tried to add some clarification on this intended behavior.

I think all your other suggestions were valid so I've put them all in. This spec will be heading toward standardization through SMPTE, so ironing out these little typos are very helpful. (Side note: It will also be useful when I can figure out how to add equation numbers in mkdocs for explicit reference rather than saying "the above" or "the below" equations...)

**Comment by vincentisambart** [comment]
Thank you for the quick fix 😊

> This spec will be heading toward standardization through SMPTE

I was a bit wondering if many people would be looking at the spec in the future and if it was really useful to make you update it, but I'm glad to know it's worth it 😁
